name: easyattend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  
  flutter_riverpod: ^2.6.1
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  mobile_scanner: ^6.0.7
  pretty_qr_code: ^3.3.0
  google_fonts: ^6.2.1
  go_router: ^14.8.1
  cloud_firestore: ^5.6.6
  flutter_svg: ^2.0.17
  geolocator: ^14.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  custom_lint:
  riverpod_lint:
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  aandroid: true
  ios: true 
  image_path: "assets/images/logo_big.png" 
  adaptive_icon_background: "#333333"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/svgs/